# Site settings
title: School of Data Mining
header-img: img/home-bg.jpg
description: "The place to start and improve your knowledge about data mining"
baseurl: ""
url: "http://school-of-data-mining.com"
twitter_username: SchoolOfDMining
github_username:  school-of-data-mining

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
